// fetch users
export const FETCH_CANDIDATE_LOADING = "FETCH_CANDIDATE_LOADING";
export const FETCH_CANDIDATE_SUCCESS = "FETCH_CANDIDATE_SUCCESS";
export const FETCH_CANDIDATE_ERROR = "FETCH_CANDIDATE_ERROR";
export const FETCH_CANDIDATE_RESET = "FETCH_CANDIDATE_RESET";

// fetch users
export const FETCH_SINGLE_CANDIDATE_LOADING = "FETCH_SINGLE_CANDIDATE_LOADING";
export const FETCH_SINGLE_CANDIDATE_SUCCESS = "FETCH_SINGLE_CANDIDATE_SUCCESS";
export const FETCH_SINGLE_CANDIDATE_ERROR = "FETCH_SINGLE_CANDIDATE_ERROR";
export const FETCH_SINGLE_CANDIDATE_RESET = "FETCH_SINGLE_CANDIDATE_RESET";

// register CANDIDATE
export const CREATE_CANDIDATE_LOADING = "CREATE_CANDIDATE_LOADING";
export const CREATE_CANDIDATE_SUCCESS = "CREATE_CANDIDATE_SUCCESS";
export const CREATE_CANDIDATE_ERROR = "CREATE_CANDIDATE_ERROR";
export const CREATE_CANDIDATE_RESET = "CREATE_CANDIDATE_RESET";

// delete CANDIDATE
export const DELETE_CANDIDATE_LOADING = "DELETE_CANDIDATE_LOADING";
export const DELETE_CANDIDATE_SUCCESS = "DELETE_CANDIDATE_SUCCESS";
export const DELETE_CANDIDATE_ERROR = "DELETE_CANDIDATE_ERROR";
export const DELETE_CANDIDATE_RESET = "DELETE_CANDIDATE_RESET";

// edit CANDIDATE
export const UPDATE_CANDIDATE_LOADING = "UPDATE_CANDIDATE_LOADING";
export const UPDATE_CANDIDATE_SUCCESS = "UPDATE_CANDIDATE_SUCCESS";
export const UPDATE_CANDIDATE_ERROR = "UPDATE_CANDIDATE_ERROR";
export const UPDATE_CANDIDATE_RESET = "UPDATE_CANDIDATE_RESET";

// upload image
export const UPLOAD_IMAGE_LOADING = "UPLOAD_IMAGE_LOADING";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";
export const UPLOAD_IMAGE_RESET = "UPLOAD_IMAGE_RESET";
