// fetch users
export const FETCH_CATEGORY_LOADING = "FETCH_CATEGORY_LOADING";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";
export const FETCH_CATEGORY_RESET = "FETCH_CATEGORY_RESET";

// fetch users
export const FETCH_SINGLE_CATEGORY_LOADING = "FETCH_SINGLE_CATEGORY_LOADING";
export const FETCH_SINGLE_CATEGORY_SUCCESS = "FETCH_SINGLE_CATEGORY_SUCCESS";
export const FETCH_SINGLE_CATEGORY_ERROR = "FETCH_SINGLE_CATEGORY_ERROR";
export const FETCH_SINGLE_CATEGORY_RESET = "FETCH_SINGLE_CATEGORY_RESET";

// register CATEGORY
export const CREATE_CATEGORY_LOADING = "CREATE_CATEGORY_LOADING";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";
export const CREATE_CATEGORY_RESET = "CREATE_CATEGORY_RESET";

// delete CATEGORY
export const DELETE_CATEGORY_LOADING = "DELETE_CATEGORY_LOADING";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";
export const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET";

// edit CATEGORY
export const UPDATE_CATEGORY_LOADING = "UPDATE_CATEGORY_LOADING";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";
export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";
