export const SEND_VOTE_LOADING = "SEND_VOTE_LOADING";
export const SEND_VOTE_SUCCESS = "SEND_VOTE_SUCCESS";
export const SEND_VOTE_ERRORS = "SEND_VOTE_ERRORS";
export const SEND_VOTE_RESET = "SEND_VOTE_RESET";

export const RELEASE_RESULTS_LOADING = "RELEASE_RESULTS_LOADING";
export const RELEASE_RESULTS_SUCCESS = "RELEASE_RESULTS_SUCCESS";
export const RELEASE_RESULTS_ERRORS = "RELEASE_RESULTS_ERRORS";
export const RELEASE_RESULTS_RESET = "RELEASE_RESULTS_RESET";

export const START_O_STOP_LOADING = "START_O_STOP_LOADING";
export const START_O_STOP_SUCCESS = "START_O_STOP_SUCCESS";
export const START_O_STOP_ERRORS = "START_O_STOP_ERRORS";
export const START_O_STOP_RESET = "START_O_STOP_RESET";

export const _GET_START_O_STOP_LOADING = "_GET_START_O_STOP_LOADING";
export const _GET_START_O_STOP_SUCCESS = "_GET_START_O_STOP_SUCCESS";
export const _GET_START_O_STOP_ERRORS = "_GET_START_O_STOP_ERRORS";
export const _GET_START_O_STOP_RESET = "_GET_START_O_STOP_RESET";
